#!/bin/bash -
#===============================================================================
#
#          FILE: deploy-servlet
#
#         USAGE: ./deploy-servlet
#
#   DESCRIPTION: Script to compile the ch1 web app and deploy it to tomcat
#===============================================================================

set -o nounset                                  # Treat unset variables as an error

# Compile
cd /usr/local/src/app

javac -classpath $CATALINA_HOME/lib/servlet-api.jar -d dist/WEB-INF/classes src/dev/andyosborne/Ch1Servlet.java

jar cvf Serv1.war -C static . -C dist .

cp Serv1.war $CATALINA_HOME/webapps

cd -

# Start Tomcat
$CATALINA_HOME/bin/startup.sh

